### ISSUE TITLE
Android   java.lang.NullPointerException

### ISSUE THREAD

**Issue by buctyoyo** [pchab/AndroidRTC#18]
when i build apk, and load in andorid 4.4.4 os, I got follow errors. when i open the url sended by app。

11-03 16:42:55.243  21404-21494/fr.pchab.AndroidRTC E/libjingle﹕ Error(webrtcvideoengine.cc:1265): webrtc: (voe_audio_processing_impl.cc:990): virtual int webrtc::VoEAudioProcessingImpl::SetTypingDetectionStatus(bool): not supported

11-03 16:43:11.594  21404-21404/fr.pchab.AndroidRTC E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: fr.pchab.AndroidRTC, PID: 21404
    java.lang.NullPointerException
            at org.webrtc.PeerConnection.addStream(PeerConnection.java:149)
            at fr.pchab.AndroidRTC.WebRtcClient$Peer.<init>(WebRtcClient.java:246)
            at fr.pchab.AndroidRTC.WebRtcClient.addPeer(WebRtcClient.java:331)
            at fr.pchab.AndroidRTC.WebRtcClient.access$1000(WebRtcClient.java:28)
            at fr.pchab.AndroidRTC.WebRtcClient$MessageHandler.onEvent(WebRtcClient.java:144)
            at com.koushikdutta.async.http.socketio.EventEmitter.onEvent(EventEmitter.java:26)
            at com.koushikdutta.async.http.socketio.SocketIOConnection$8$1.run(SocketIOConnection.java:396)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5014)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)
11

**Comment by bemonio** [comment]
Hi!, how to solve this NullPointerException?
