### ISSUE TITLE
switch camera

### ISSUE THREAD

**Issue by arunsparki** [pchab/AndroidRTC#193]
Hi ,
I get an issue when i am adding switch camera function in RtcActivity.java
  java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:545)
        at android.hardware.Camera.open(Camera.java:385)
        at org.webrtc.VideoCapturerAndroid.startCaptureOnCameraThread(VideoCapturerAndroid.java:414)
        at org.webrtc.VideoCapturerAndroid.access$300(VideoCapturerAndroid.java:74)
        at org.webrtc.VideoCapturerAndroid$2.run(VideoCapturerAndroid.java:401)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at org.webrtc.VideoCapturerAndroid$CameraThread.run(VideoCapturerAndroid.java:368)

**Comment by haojiufeng** [comment]
videoCapturerAndroid.switchCamera(new Runnable() {
            @Override
            public void run() {
            }
        }); // or  videoCapturerAndroid.switchCamera(null);

这两种方式都是可以的，需要注意videoCapturerAndroid 为全局唯一变量
