### ISSUE TITLE
Scheme 'wss' not registered

### ISSUE THREAD

**Issue by i68040** [pchab/AndroidRTC#25]
I'm attempting to hit a secure web socket endpoint and get this error. Any suggestions?

02-08 22:45:13.452  22103-22178/? E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: fr.pchab.AndroidRTC, PID: 22103
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalStateException: Scheme 'wss' not registered.
            at org.apache.http.conn.scheme.SchemeRegistry.getScheme(SchemeRegistry.java:80)
            at org.apache.http.impl.conn.ProxySelectorRoutePlanner.determineRoute(ProxySelectorRoutePlanner.java:157)
            at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:596)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:293)
            at org.apache.http.impl.client.AbstractHttpClient$1.executeRequestSending(AbstractHttpClient.java:636)
            at org.apache.http.impl.client.naf.redirect.NafRequestExecutorWrapperRedirectionHandler.executeRequestSendingUsual(NafRequestExecutorWrapperRedirectionHandler.java:96)
            at org.apache.http.impl.client.naf.redirect.NafRequestExecutorWrapperRedirectionHandler.executeRequestSending(NafRequestExecutorWrapperRedirectionHandler.java:73)
            at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.sendFirstRequest(NafHttpAuthStrategyDefault.java:488)
            at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.performAuthExecutionUnsafe(NafHttpAuthStrategyDefault.java:389)
            at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.performAuthExecution(NafHttpAuthStrategyDefault.java:200)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:566)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:512)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:490)
            at android.net.http.AndroidHttpClient.execute(AndroidHttpClient.java:303)
            at com.koushikdutta.http.AsyncHttpClient$1.doInBackground(AsyncHttpClient.java:72)
            at com.koushikdutta.http.AsyncHttpClient$1.doInBackground(AsyncHttpClient.java:63)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by pchab** [comment]
I've changed the websocket lib. Please test and see if it solves your issue. Btw the socket.io lib is not exactly a websocket lib : it first does a http negociation then switch to websocket if possible.
If you want to use websockets only, you should probably change the library to use something like autobahn (and a pure websocket server).
