### ISSUE TITLE
AndroidRTC Crash

### ISSUE THREAD

**Issue by zhongkun** [pchab/AndroidRTC#39]
12-26 19:24:26.360  23340-23662/fr.pchab.androidrtc E/AndroidRuntime﹕ FATAL EXCEPTION: AudioRecordJavaThread
    Process: fr.pchab.androidrtc, PID: 23340
    java.lang.AssertionError: Expected condition to be true
            at org.webrtc.voiceengine.WebRtcAudioRecord.assertTrue(WebRtcAudioRecord.java:278)
            at org.webrtc.voiceengine.WebRtcAudioRecord.access$300(WebRtcAudioRecord.java:30)
            at org.webrtc.voiceengine.WebRtcAudioRecord$AudioRecordThread.run(WebRtcAudioRecord.java:91)

**Comment by pchab** [comment]
I'll need more informations:
What steps led to this ? Does this happen everytime / often / rarely ?

**Comment by sharatmohan** [comment]
I always get this when calling from browser to android

07-21 12:41:04.670    3411-3533/fr.pchab.AndroidRTC D/WebRtcAudioRecord? InitRecording(sampleRate=44100)
07-21 12:41:04.670    3411-3533/fr.pchab.AndroidRTC D/WebRtcAudioRecord? AudioRecord.getMinBufferSize: 4096
07-21 12:41:04.670    3411-3533/fr.pchab.AndroidRTC D/WebRtcAudioRecord? bufferSizeInBytes: 4096
07-21 12:41:04.680      153-153/? W/AudioPolicyManagerBase? getInput() could not find profile for device 100000, samplingRate 44100, format 1,channelMask 0010
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC E/AudioRecord? Could not get audio input for record source 7
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC E/AudioRecord-JNI? Error creating AudioRecord instance: initialization check failed.
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC E/AudioRecord-Java? [ android.media.AudioRecord ] Error code -20 when initializing native AudioRecord object.
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC W/System.err? java.lang.AssertionError: Expected condition to be true
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC W/System.err? at org.webrtc.voiceengine.WebRtcAudioRecord.assertTrue(WebRtcAudioRecord.java:278)
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC W/System.err? at org.webrtc.voiceengine.WebRtcAudioRecord.InitRecording(WebRtcAudioRecord.java:221)
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC W/System.err? at dalvik.system.NativeStart.run(Native Method)
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC E/rtc? #
    # Fatal error in ../../webrtc/modules/audio_device/android/audio_record_jni.cc, line 141
    # Check failed: !jni->ExceptionCheck()
    #
    #
07-21 12:41:04.680    3411-3533/fr.pchab.AndroidRTC A/libc? Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 3533 (Thread-3127)

**Comment by KristjanLiiva** [comment]
@zhongkun I ran into this, when I used another application that uses voice recognition before using AndroidRTC. So I would assume that the AndroidRTC could not access the microphone, and just crashes when it tries to do so.

**Comment by ZengHongHua** [comment]
me to the same question, because a application was use mic, stop it .
