### ISSUE TITLE
ProjectRTC server error while starting

### ISSUE THREAD

**Issue by wsxtesting** [pchab/AndroidRTC#62]
While I am running ProjectRTC server it is throwing below error.

SyntaxError: Unexpected identifier in F:\ProjectRTC\views\index.ejs w
hile compiling ejs
    at Function (native)
    at Object.Template.compile (F:\ProjectRTC\node_modules\ejs\lib\ejs.js:464:12)
    at Object.compile (F:\ProjectRTC\node_modules\ejs\lib\ejs.js:288:16)
    at handleCache (F:\ProjectRTC\node_modules\ejs\lib\ejs.js:147:16)
    at View.exports.renderFile [as engine](F:ProjectRTCnode_modulesejslibejs.js:350:14)
    at View.render (F:\ProjectRTC\node_modules\express\lib\view.js:126:8)
    at tryRender (F:\ProjectRTC\node_modules\express\lib\application.js:639:10)
    at EventEmitter.render (F:\ProjectRTC\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (F:\ProjectRTC\node_modules\express\lib\response.js:961:7)
    at index (F:\ProjectRTC\app\routes.js:5:9)

Has anyone experienced it before.

**Comment by mrcmrc** [comment]
I have the some error

**Comment by johfpardo** [comment]
You should use ejs 1.0. install it using this command

npm install ejs@1.0

I had the same problem, then I used this command and It worked !!

I found the solution here: 
https://github.com/pchab/ProjectRTC/issues/20
