### ISSUE TITLE
ANR in glsurfaceview's on pause

### ISSUE THREAD

**Issue by bangarharshit** [pchab/AndroidRTC#73]
I am getting ANR while doing GLSurfaceView's onpause sometimes. It is in RTCActivity's onpause

```
DALVIK THREADS (49):
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x73fdb480 self=0xb83c04c0
  | sysTid=23407 nice=0 cgrp=apps/bg_non_interactive sched=0/0 handle=0xb6fd2ec8
  | state=S schedstat=( 0 0 0 ) utm=781 stm=88 core=1 HZ=100
  | stack=0xbe14c000-0xbe14e000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x3c519060> (a android.opengl.GLSurfaceView$GLThreadManager)
  at android.opengl.GLSurfaceView$GLThread.onPause(GLSurfaceView.java:1647)
  - locked <0x3c519060> (a android.opengl.GLSurfaceView$GLThreadManager)
  at android.opengl.GLSurfaceView.onPause(GLSurfaceView.java:550)
  at com.sandwich.chatclient.webrtc.RtcActivity.onPause(RtcActivity.java:187)
  at android.app.Activity.performPause(Activity.java:6064)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1317)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3292)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3259)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3234)
  at android.app.ActivityThread.access$1000(ActivityThread.java:148)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5312)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by AndyCaoGitHub** [comment]
how to resolve it?

**Comment by tpnet** [comment]
Hello,How to resolve it?
